import {StyleSheet} from 'react-native';
import {ThemePalette} from './appConfig';

export function createStyles(theme: ThemePalette) {
  return StyleSheet.create({
    safeArea: {flex: 1, backgroundColor: theme.background},
    root: {flex: 1, backgroundColor: theme.background},
    orbPrimary: {
      position: 'absolute',
      top: -120,
      right: -80,
      width: 240,
      height: 240,
      borderRadius: 999,
      backgroundColor: theme.backgroundSecondary,
      opacity: 0.45,
    },
    orbSecondary: {
      position: 'absolute',
      left: -110,
      top: 340,
      width: 180,
      height: 180,
      borderRadius: 999,
      backgroundColor: theme.accentSoft,
      opacity: 0.2,
    },
    topBar: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
      paddingHorizontal: 20,
      paddingTop: 8,
      paddingBottom: 8,
    },
    menuButton: {
      width: 52,
      height: 52,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.hero,
      borderWidth: 1,
      borderColor: theme.line,
      shadowColor: theme.shadow,
      shadowOpacity: 0.18,
      shadowRadius: 14,
      shadowOffset: {width: 0, height: 8},
      elevation: 3,
    },
    menuButtonText: {color: theme.heroText, fontSize: 20, fontWeight: '900', letterSpacing: 1},
    topBarTextBlock: {flex: 1},
    topBarBadge: {
      maxWidth: 132,
      minHeight: 48,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 16,
      backgroundColor: theme.panelAlt,
      borderWidth: 1,
      borderColor: theme.line,
      alignItems: 'center',
      justifyContent: 'center',
    },
    topBarBadgeText: {
      color: theme.text,
      fontSize: 11,
      fontWeight: '900',
      letterSpacing: 0.8,
      textTransform: 'uppercase',
      textAlign: 'center',
    },
    topBarEyebrow: {
      color: theme.accentStrong,
      fontSize: 11,
      fontWeight: '800',
      letterSpacing: 1.8,
      textTransform: 'uppercase',
    },
    topBarTitle: {
      color: theme.text,
      fontSize: 30,
      lineHeight: 34,
      fontWeight: '900',
      marginTop: 2,
    },
    content: {paddingHorizontal: 20, paddingTop: 8, paddingBottom: 28, gap: 14},
    screenBlock: {gap: 14},
    hero: {
      backgroundColor: theme.panel,
      borderRadius: 24,
      paddingHorizontal: 18,
      paddingTop: 16,
      paddingBottom: 16,
      borderWidth: 1,
      borderColor: theme.line,
      shadowColor: theme.shadow,
      shadowOpacity: 0.18,
      shadowRadius: 12,
      shadowOffset: {width: 0, height: 8},
      elevation: 2,
    },
    heroTopRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 10,
      marginBottom: 8,
    },
    heroLabel: {
      color: theme.accentStrong,
      fontSize: 11,
      fontWeight: '900',
      letterSpacing: 1.4,
      textTransform: 'uppercase',
    },
    heroMeta: {
      color: theme.textMuted,
      fontSize: 12,
      fontWeight: '700',
    },
    heroTitle: {color: theme.text, fontSize: 24, lineHeight: 28, fontWeight: '900'},
    balanceCard: {
      backgroundColor: theme.hero,
      borderRadius: 28,
      padding: 20,
      borderWidth: 1,
      borderColor: theme.line,
    },
    balanceLabel: {
      color: theme.heroText,
      opacity: 0.72,
      fontSize: 12,
      fontWeight: '800',
      textTransform: 'uppercase',
      letterSpacing: 1,
    },
    balanceValue: {
      fontSize: 34,
      lineHeight: 38,
      fontWeight: '900',
      marginTop: 8,
    },
    balanceMetaRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 16,
      borderTopWidth: 1,
      borderTopColor: 'rgba(255,255,255,0.12)',
      paddingTop: 14,
    },
    balanceMetaItem: {flex: 1},
    balanceMetaLabel: {
      color: theme.heroText,
      opacity: 0.68,
      fontSize: 12,
      fontWeight: '700',
    },
    balanceMetaValue: {
      fontSize: 18,
      fontWeight: '900',
      marginTop: 4,
    },
    balanceDivider: {
      width: 1,
      alignSelf: 'stretch',
      backgroundColor: 'rgba(255,255,255,0.12)',
      marginHorizontal: 14,
    },
    card: {
      backgroundColor: theme.panel,
      borderRadius: 24,
      padding: 18,
      borderWidth: 1,
      borderColor: theme.line,
      gap: 12,
      shadowColor: theme.shadow,
      shadowOpacity: 0.18,
      shadowRadius: 12,
      shadowOffset: {width: 0, height: 8},
      elevation: 2,
    },
    sectionTitle: {color: theme.text, fontSize: 20, fontWeight: '900'},
    sectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 12,
      paddingBottom: 4,
    },
    sectionHeaderCompact: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    sectionHint: {
      minWidth: 34,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 999,
      backgroundColor: theme.panelAlt,
      color: theme.textMuted,
      textAlign: 'center',
      fontSize: 12,
      fontWeight: '800',
    },
    rowBetween: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 12},
    fieldBlock: {gap: 8},
    fieldLabel: {
      color: theme.textMuted,
      fontSize: 12,
      fontWeight: '700',
    },
    input: {
      minHeight: 52,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: theme.line,
      paddingHorizontal: 16,
      color: theme.text,
      backgroundColor: theme.panelAlt,
    },
    secondaryButton: {
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 16,
      backgroundColor: theme.accentSoft,
    },
    secondaryButtonText: {color: theme.accentStrong, fontWeight: '900'},
    monthRow: {flexDirection: 'row', gap: 12, paddingVertical: 2},
    monthChip: {
      paddingHorizontal: 14,
      paddingVertical: 12,
      borderRadius: 16,
      backgroundColor: theme.panelAlt,
      borderWidth: 1,
      borderColor: theme.line,
    },
    monthChipSelected: {backgroundColor: theme.hero, borderColor: theme.hero},
    monthChipText: {color: theme.text, fontWeight: '900', textTransform: 'capitalize'},
    monthChipTextSelected: {color: theme.heroText},
    metricCard: {
      backgroundColor: theme.panelAlt,
      borderRadius: 20,
      padding: 16,
      borderWidth: 1,
      borderColor: theme.line,
      overflow: 'hidden',
    },
    metricAccent: {position: 'absolute', left: 0, top: 16, bottom: 16, width: 6, borderRadius: 999},
    metricLabel: {
      color: theme.textMuted,
      fontSize: 12,
      fontWeight: '800',
      letterSpacing: 1,
      paddingLeft: 10,
      textTransform: 'uppercase',
    },
    metricValue: {fontSize: 26, fontWeight: '900', marginTop: 8, paddingLeft: 10},
    typeRow: {flexDirection: 'row', gap: 10},
    typeChip: {
      flex: 1,
      paddingVertical: 12,
      borderRadius: 16,
      alignItems: 'center',
      backgroundColor: theme.panelAlt,
      borderWidth: 1,
      borderColor: theme.line,
    },
    typeChipSelected: {backgroundColor: theme.hero, borderColor: theme.hero},
    typeChipText: {color: theme.text, fontWeight: '800'},
    typeChipTextSelected: {color: theme.heroText},
    primaryButton: {
      minHeight: 56,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 16,
      backgroundColor: theme.accent,
    },
    primaryButtonText: {color: theme.accentText, fontWeight: '900', fontSize: 15},
    sectionHintText: {color: theme.textMuted},
    legendText: {color: theme.textMuted, fontSize: 11, flex: 1, textAlign: 'right'},
    chartCard: {
      backgroundColor: theme.panelAlt,
      borderRadius: 18,
      padding: 14,
      minHeight: 210,
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.line,
    },
    chartRow: {flexDirection: 'row', alignItems: 'flex-end', gap: 12},
    chartGroup: {width: 78, alignItems: 'center', gap: 8},
    barArea: {
      height: 124,
      width: '100%',
      flexDirection: 'row',
      alignItems: 'flex-end',
      justifyContent: 'center',
      gap: 7,
    },
    bar: {width: 16, minHeight: 4, borderRadius: 999},
    expenseBar: {backgroundColor: theme.expense},
    incomeBar: {backgroundColor: theme.income},
    chartDate: {color: theme.text, fontSize: 11, fontWeight: '700'},
    netValue: {fontSize: 11, fontWeight: '800', textAlign: 'center'},
    historyList: {gap: 10},
    historyItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 12,
      padding: 14,
      borderRadius: 18,
      backgroundColor: theme.panelAlt,
      borderWidth: 1,
      borderColor: theme.line,
    },
    historyTextBlock: {flex: 1},
    historyTitle: {color: theme.text, fontSize: 16, fontWeight: '800'},
    historyMeta: {color: theme.textMuted, marginTop: 4},
    historyActions: {alignItems: 'flex-end', gap: 6},
    historyAmount: {fontSize: 16, fontWeight: '900'},
    deleteText: {color: theme.accentStrong, fontWeight: '700'},
    emptyText: {color: theme.textMuted, textAlign: 'center', lineHeight: 20},
    calculatorDisplay: {backgroundColor: theme.hero, borderRadius: 22, padding: 18, gap: 10},
    expressionText: {color: theme.heroText, opacity: 0.72, fontSize: 18},
    resultText: {color: theme.heroText, fontSize: 34, fontWeight: '900'},
    calculatorGrid: {gap: 10},
    calculatorRow: {flexDirection: 'row', gap: 10},
    calcButton: {
      flex: 1,
      minHeight: 54,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.panelAlt,
      borderWidth: 1,
      borderColor: theme.line,
    },
    operatorButton: {backgroundColor: theme.accentSoft},
    clearButton: {backgroundColor: theme.expense, borderColor: theme.expense},
    calcButtonText: {color: theme.text, fontSize: 18, fontWeight: '800'},
    equalsButton: {
      minHeight: 54,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.accent,
      marginTop: 4,
    },
    equalsButtonText: {color: theme.accentText, fontWeight: '900', fontSize: 16},
    codePreview: {
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: 210,
      backgroundColor: '#FFFFFF',
      borderRadius: 18,
      padding: 16,
      borderWidth: 1,
      borderColor: theme.line,
    },
    pathText: {color: theme.text, lineHeight: 20},
    overlay: {...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(15, 23, 42, 0.28)'},
    sidebar: {
      position: 'absolute',
      top: 0,
      left: 0,
      bottom: 0,
      width: 320,
      backgroundColor: theme.panel,
      paddingTop: 26,
      paddingHorizontal: 18,
      paddingBottom: 24,
      borderTopRightRadius: 28,
      borderBottomRightRadius: 28,
      borderWidth: 1,
      borderColor: theme.line,
      gap: 14,
    },
    sidebarHeader: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between'},
    sidebarTitle: {color: theme.text, fontSize: 24, fontWeight: '900'},
    sidebarCloseButton: {
      width: 40,
      height: 40,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.panelAlt,
      borderWidth: 1,
      borderColor: theme.line,
    },
    sidebarClose: {color: theme.text, fontSize: 24, lineHeight: 24},
    sidebarSection: {gap: 10},
    sidebarSectionLabel: {
      color: theme.textMuted,
      fontSize: 12,
      fontWeight: '700',
      letterSpacing: 1,
      textTransform: 'uppercase',
    },
    optionRow: {flexDirection: 'row', gap: 10},
    optionChip: {
      minWidth: 64,
      paddingHorizontal: 12,
      paddingVertical: 11,
      borderRadius: 14,
      backgroundColor: theme.panelAlt,
      borderWidth: 1,
      borderColor: theme.line,
      alignItems: 'center',
    },
    optionChipSelected: {backgroundColor: theme.hero, borderColor: theme.hero},
    optionChipText: {color: theme.text, fontWeight: '800'},
    optionChipTextSelected: {color: theme.heroText},
    themeOption: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      padding: 12,
      borderRadius: 16,
      backgroundColor: theme.panelAlt,
      borderWidth: 1,
      borderColor: theme.line,
    },
    themeOptionSelected: {borderColor: theme.accent, backgroundColor: theme.accentSoft},
    themePreview: {
      width: 38,
      height: 38,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
    },
    themePreviewDot: {width: 14, height: 14, borderRadius: 999},
    themeOptionText: {color: theme.text, fontWeight: '800', fontSize: 15},
    sidebarItem: {
      paddingHorizontal: 14,
      paddingVertical: 16,
      borderRadius: 18,
      backgroundColor: theme.panelAlt,
      borderWidth: 1,
      borderColor: theme.line,
    },
    sidebarItemSelected: {backgroundColor: theme.hero, borderColor: theme.hero},
    sidebarItemTitle: {color: theme.text, fontSize: 16, fontWeight: '900'},
    sidebarItemTitleSelected: {color: theme.heroText},
  });
}
