import {StyleSheet} from 'react-native';
import {ThemePalette} from './appConfig';

export function createStyles(theme: ThemePalette) {
  return StyleSheet.create({
    safeArea: {flex: 1, backgroundColor: theme.background},
    root: {flex: 1, backgroundColor: theme.background},
    orbPrimary: {
      position: 'absolute',
      top: -40,
      right: -10,
      width: 220,
      height: 220,
      borderRadius: 999,
      backgroundColor: theme.backgroundSecondary,
      opacity: 0.9,
    },
    orbSecondary: {
      position: 'absolute',
      left: -60,
      top: 180,
      width: 180,
      height: 180,
      borderRadius: 999,
      backgroundColor: theme.accentSoft,
      opacity: 0.45,
    },
    topBar: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
      paddingHorizontal: 18,
      paddingTop: 10,
      paddingBottom: 6,
    },
    menuButton: {
      width: 52,
      height: 52,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.hero,
      borderWidth: 1,
      borderColor: theme.line,
      shadowColor: theme.shadow,
      shadowOpacity: 1,
      shadowRadius: 18,
      shadowOffset: {width: 0, height: 10},
      elevation: 4,
    },
    menuButtonText: {color: theme.heroText, fontSize: 24, fontWeight: '800'},
    topBarTextBlock: {flex: 1},
    topBarBadge: {
      minWidth: 58,
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderRadius: 16,
      backgroundColor: theme.panel,
      borderWidth: 1,
      borderColor: theme.line,
      alignItems: 'center',
      justifyContent: 'center',
    },
    topBarBadgeText: {
      color: theme.text,
      fontSize: 12,
      fontWeight: '900',
      letterSpacing: 1,
    },
    topBarEyebrow: {
      color: theme.textMuted,
      fontSize: 12,
      fontWeight: '700',
      letterSpacing: 1.2,
      textTransform: 'uppercase',
    },
    topBarTitle: {
      color: theme.text,
      fontSize: 28,
      lineHeight: 32,
      fontWeight: '900',
      marginTop: 2,
    },
    topBarSubtitle: {color: theme.textMuted, fontSize: 13, lineHeight: 18, marginTop: 2},
    content: {padding: 18, paddingTop: 8, paddingBottom: 28, gap: 16},
    screenBlock: {gap: 16},
    infoStrip: {
      gap: 10,
    },
    infoPill: {
      backgroundColor: theme.panel,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: theme.line,
      paddingHorizontal: 14,
      paddingVertical: 12,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      shadowColor: theme.shadow,
      shadowOpacity: 0.45,
      shadowRadius: 12,
      shadowOffset: {width: 0, height: 8},
      elevation: 2,
    },
    infoLabel: {
      color: theme.textMuted,
      fontSize: 11,
      fontWeight: '800',
      letterSpacing: 0.8,
      textTransform: 'uppercase',
    },
    infoValue: {
      color: theme.text,
      fontSize: 14,
      fontWeight: '800',
      flex: 1,
      textAlign: 'right',
      marginLeft: 12,
    },
    hero: {
      backgroundColor: theme.hero,
      borderRadius: 30,
      padding: 24,
      borderWidth: 1,
      borderColor: theme.line,
      overflow: 'hidden',
      minHeight: 220,
    },
    heroGlowLarge: {
      position: 'absolute',
      width: 220,
      height: 220,
      borderRadius: 999,
      backgroundColor: theme.heroSecondary,
      opacity: 0.16,
      top: -48,
      right: -36,
    },
    heroGlowSmall: {
      position: 'absolute',
      width: 120,
      height: 120,
      borderRadius: 999,
      backgroundColor: theme.panel,
      opacity: 0.08,
      bottom: -24,
      right: 40,
    },
    heroBadge: {
      alignSelf: 'flex-start',
      paddingHorizontal: 12,
      paddingVertical: 7,
      borderRadius: 999,
      backgroundColor: theme.heroSecondary,
      marginBottom: 14,
    },
    heroBadgeText: {color: theme.heroText, fontSize: 11, fontWeight: '800', letterSpacing: 1.6},
    heroTitle: {color: theme.heroText, fontSize: 31, lineHeight: 37, fontWeight: '900'},
    heroText: {color: theme.heroText, opacity: 0.82, fontSize: 15, lineHeight: 23, marginTop: 12},
    card: {
      backgroundColor: theme.panel,
      borderRadius: 26,
      padding: 18,
      borderWidth: 1,
      borderColor: theme.line,
      gap: 12,
      shadowColor: theme.shadow,
      shadowOpacity: 1,
      shadowRadius: 18,
      shadowOffset: {width: 0, height: 10},
      elevation: 3,
    },
    sectionTitle: {color: theme.text, fontSize: 20, fontWeight: '800'},
    sectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 12,
      paddingBottom: 4,
      marginBottom: 2,
      borderBottomWidth: 1,
      borderBottomColor: theme.line,
    },
    rowBetween: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 12},
    input: {
      minHeight: 52,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: theme.line,
      paddingHorizontal: 14,
      color: theme.text,
      backgroundColor: theme.panelAlt,
    },
    secondaryButton: {
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 14,
      backgroundColor: theme.accentSoft,
    },
    secondaryButtonText: {color: theme.accentStrong, fontWeight: '800'},
    monthRow: {flexDirection: 'row', gap: 10, paddingVertical: 2},
    monthChip: {
      paddingHorizontal: 14,
      paddingVertical: 12,
      borderRadius: 18,
      backgroundColor: theme.panelAlt,
      borderWidth: 1,
      borderColor: theme.line,
    },
    monthChipSelected: {backgroundColor: theme.hero, borderColor: theme.hero},
    monthChipText: {color: theme.text, fontWeight: '800', textTransform: 'capitalize'},
    monthChipTextSelected: {color: theme.heroText},
    summaryRow: {gap: 12},
    metricCard: {
      backgroundColor: theme.panel,
      borderRadius: 24,
      padding: 18,
      borderWidth: 1,
      borderColor: theme.line,
      overflow: 'hidden',
    },
    metricAccent: {position: 'absolute', left: 0, top: 0, bottom: 0, width: 5},
    metricLabel: {color: theme.textMuted, fontSize: 13, fontWeight: '700', paddingLeft: 6},
    metricValue: {fontSize: 28, fontWeight: '900', marginTop: 8, paddingLeft: 6},
    typeRow: {flexDirection: 'row', gap: 10},
    typeChip: {
      flex: 1,
      paddingVertical: 12,
      borderRadius: 16,
      alignItems: 'center',
      backgroundColor: theme.panelAlt,
      borderWidth: 1,
      borderColor: theme.line,
    },
    typeChipSelected: {backgroundColor: theme.hero, borderColor: theme.hero},
    typeChipText: {color: theme.text, fontWeight: '800'},
    typeChipTextSelected: {color: theme.heroText},
    primaryButton: {
      minHeight: 54,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 18,
      backgroundColor: theme.accent,
    },
    primaryButtonText: {color: theme.accentText, fontWeight: '800', fontSize: 15},
    legendText: {color: theme.textMuted, fontSize: 12, flex: 1, textAlign: 'right'},
    chartCard: {
      backgroundColor: theme.panelAlt,
      borderRadius: 20,
      padding: 14,
      minHeight: 230,
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.line,
    },
    chartRow: {flexDirection: 'row', alignItems: 'flex-end', gap: 12},
    chartGroup: {width: 78, alignItems: 'center', gap: 8},
    barArea: {
      height: 124,
      width: '100%',
      flexDirection: 'row',
      alignItems: 'flex-end',
      justifyContent: 'center',
      gap: 7,
    },
    bar: {width: 16, minHeight: 4, borderRadius: 999},
    expenseBar: {backgroundColor: theme.expense},
    incomeBar: {backgroundColor: theme.income},
    chartDate: {color: theme.text, fontSize: 11, fontWeight: '700'},
    netValue: {fontSize: 11, fontWeight: '800', textAlign: 'center'},
    historyList: {gap: 10},
    historyItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 12,
      padding: 14,
      borderRadius: 18,
      backgroundColor: theme.panelAlt,
      borderWidth: 1,
      borderColor: theme.line,
    },
    historyTextBlock: {flex: 1},
    historyTitle: {color: theme.text, fontSize: 16, fontWeight: '800'},
    historyMeta: {color: theme.textMuted, marginTop: 4},
    historyActions: {alignItems: 'flex-end', gap: 6},
    historyAmount: {fontSize: 16, fontWeight: '900'},
    deleteText: {color: theme.accentStrong, fontWeight: '700'},
    emptyText: {color: theme.textMuted, textAlign: 'center', lineHeight: 20},
    calculatorDisplay: {backgroundColor: theme.hero, borderRadius: 22, padding: 18, gap: 8},
    expressionText: {color: theme.heroText, opacity: 0.72, fontSize: 18},
    resultText: {color: theme.heroText, fontSize: 34, fontWeight: '900'},
    calculatorGrid: {gap: 10},
    calculatorRow: {flexDirection: 'row', gap: 10},
    calcButton: {
      flex: 1,
      minHeight: 54,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.panelAlt,
      borderWidth: 1,
      borderColor: theme.line,
    },
    operatorButton: {backgroundColor: theme.accentSoft},
    clearButton: {backgroundColor: theme.expense, borderColor: theme.expense},
    calcButtonText: {color: theme.text, fontSize: 18, fontWeight: '800'},
    equalsButton: {
      minHeight: 56,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.accent,
      marginTop: 4,
    },
    equalsButtonText: {color: theme.accentText, fontWeight: '900', fontSize: 16},
    codePreview: {
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: 210,
      backgroundColor: '#FFFFFF',
      borderRadius: 20,
      padding: 16,
      borderWidth: 1,
      borderColor: theme.line,
    },
    pathText: {color: theme.text, lineHeight: 20},
    overlay: {...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(15, 23, 42, 0.28)'},
    sidebar: {
      position: 'absolute',
      top: 0,
      left: 0,
      bottom: 0,
      width: 320,
      backgroundColor: theme.panel,
      paddingTop: 28,
      paddingHorizontal: 18,
      paddingBottom: 24,
      borderTopRightRadius: 28,
      borderBottomRightRadius: 28,
      borderWidth: 1,
      borderColor: theme.line,
      gap: 14,
    },
    sidebarHeader: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between'},
    sidebarTitle: {color: theme.text, fontSize: 24, fontWeight: '900'},
    sidebarCloseButton: {
      width: 40,
      height: 40,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.panelAlt,
      borderWidth: 1,
      borderColor: theme.line,
    },
    sidebarClose: {color: theme.text, fontSize: 24, lineHeight: 24},
    sidebarSection: {gap: 10},
    sidebarSectionLabel: {
      color: theme.textMuted,
      fontSize: 12,
      fontWeight: '700',
      letterSpacing: 1,
      textTransform: 'uppercase',
    },
    optionRow: {flexDirection: 'row', gap: 10},
    optionChip: {
      minWidth: 64,
      paddingHorizontal: 12,
      paddingVertical: 11,
      borderRadius: 14,
      backgroundColor: theme.panelAlt,
      borderWidth: 1,
      borderColor: theme.line,
      alignItems: 'center',
    },
    optionChipSelected: {backgroundColor: theme.hero, borderColor: theme.hero},
    optionChipText: {color: theme.text, fontWeight: '800'},
    optionChipTextSelected: {color: theme.heroText},
    themeOption: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      padding: 12,
      borderRadius: 16,
      backgroundColor: theme.panelAlt,
      borderWidth: 1,
      borderColor: theme.line,
    },
    themeOptionSelected: {borderColor: theme.accent, backgroundColor: theme.accentSoft},
    themePreview: {
      width: 38,
      height: 38,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
    },
    themePreviewDot: {width: 14, height: 14, borderRadius: 999},
    themeOptionText: {color: theme.text, fontWeight: '800', fontSize: 15},
    sidebarItem: {
      padding: 14,
      borderRadius: 18,
      backgroundColor: theme.panelAlt,
      borderWidth: 1,
      borderColor: theme.line,
      gap: 4,
    },
    sidebarItemSelected: {backgroundColor: theme.hero, borderColor: theme.hero},
    sidebarItemTitle: {color: theme.text, fontSize: 16, fontWeight: '900'},
    sidebarItemTitleSelected: {color: theme.heroText},
    sidebarItemSubtitle: {color: theme.textMuted, fontSize: 12, lineHeight: 18},
  });
}
